formatter: "markdown table" # this is required

version: "0.16"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Simple example

  This Examples crates a budget and cloudwatch alarm and allows them to publish to the sns topics created by the```terraform-aws-send-alarms-to-msteams``` module.

  # Example Usage

  ```shell
  terraform init
  terraform plan
  terraform apply
  ```

  This example may create resources which cost money. Run ```terraform destroy``` when you don't need the resources.

  {{ .Inputs }}

  {{ .Modules }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}

output:
  file: "readme.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
